### ISSUE TITLE
Dark mode - Low contrast for table headers within tasks

### ISSUE THREAD

**Issue by ethyoo** [go-vikunja/vikunja#253]
### Description

For dark mode: Could the default CSS for the table header be modified to increase contrast between the background and the header text?

Changing [line 835 in the Tiptap editor](https://github.com/go-vikunja/vikunja/blob/ecbefdb9216877cf247c03faab479ef363db5d89/frontend/src/components/input/editor/TipTap.vue#L835) to a darker color OR adding something like `color:#000` to that section should be sufficient.

I am using v0.23.0 and this issue applies to all browsers. I am using a self-hosted instance, but I was able to reproduce it on the demo instance.

### Vikunja Version

0.23.0

### Browser and version

Firefox v124.0.2 and Chromium

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![Tables in a task](https://github.com/go-vikunja/vikunja/assets/90781689/38f6b9e0-7884-4d4e-8734-623173093a96)

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/26ada628a2363dffd0317e9dc08aa0d80d004ceb, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).

It now looks like this:

![image](https://github.com/go-vikunja/vikunja/assets/13721712/85d98b25-d3d0-4ffc-9db3-a988ef282c6e)
