### ISSUE TITLE
quick add magic repeating tasks not working correctrly

### ISSUE THREAD

**Issue by sergue2** [go-vikunja/vikunja#271]
### Description

There seems to be a bug in adding a repeating tasks via quick add magic.
This only works for days.
Unfortunately, it does not work with weeks, months years.

### Vikunja Version

v0.23.0

### Browser and version

Firefox, Chrome and Desktop App

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Can you provide an example query which does not work?

**Comment by kolaente** [comment]
Resolved in 9f604eca79fae17cbd27d50c2ee36e37224ef1f8.

Originally, it was possible to specify repeating intervals for months or years. This was actually misleading because the interval would be converted to seconds under the hood, causing all kinds of problems with leap years and months with 30 vs 31 days. Because of that, the options for month and year were removed in 7746d3916157e43fca7a24e2a768f7fb83136cf1 to make it clear what these actually meant.
Now, since we do have a repeating mode "Monthly", this commit changes the behavior to repeat a task monthly when it was specified as "every month", but only that. All other cases were removed from the docs since they are not actually supported.

**Comment by sergue2** [comment]
this is somewhat impractical because, as you said, each month has a different number of days.
Just out of interest: Why don't you use the date format for these repeating tasks instead of converting everything into seconds?
Background:
We have many tasks that always have to be completed on the 15th of each month, for example.

**Comment by hesne** [comment]
> Resolved in [9f604ec](https://github.com/go-vikunja/vikunja/commit/9f604eca79fae17cbd27d50c2ee36e37224ef1f8).
> 
> Now, since we do have a repeating mode "Monthly", this commit changes the behavior to repeat a task monthly when it was specified as "every month", but only that. All other cases were removed from the docs since they are not actually supported.

Could you please clarify where I can find "monthly"? I can only see every XX hours/days/weeks

![grafik](https://github.com/go-vikunja/vikunja/assets/5982298/87bed480-1dcb-4c51-90c2-c8f4e651c9dd)

**Comment by kolaente** [comment]
> this is somewhat impractical because, as you said, each month has a different number of days.
Just out of interest: Why don't you use the date format for these repeating tasks instead of converting everything into seconds?
Background:
We have many tasks that always have to be completed on the 15th of each month, for example.

@sergue2 This is exactly what monthly repeat mode is for. Set it to repeat monthly and it will only increase the month by 1 every time you mark it done.

> Could you please clarify where I can find "monthly"? I can only see every XX hours/days/weeks

@hesne Right under the dropdown "Wiederholungsmodus".

**Comment by hesne** [comment]
> @hesne Right under the dropdown "Wiederholungsmodus".
![grafik](https://github.com/go-vikunja/vikunja/assets/5982298/e3ef0cc3-0600-48f5-a4dd-a5e7971c102d)

There is no monthly
