### ISSUE TITLE
Filter show done tasks dont work

### ISSUE THREAD

**Issue by neodata83** [go-vikunja/vikunja#296]
### Description

Hello 

The Filter to Show done tasks doesnt seems to be working. When i look in the Examples the Filter Rule to Show the done tasks must be "done = true" because "done = false" shows me all unfinished tasks.

### Vikunja Version

24.1

### Browser and version

Chromium Version 125.0.6422.76

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
By default, the list view has a filter set to show only done tasks (you can change that in the view settings). If you set a filter via the popup on the view, that will be combined with the filter set for the list view. So, if you set a filter `done = true` it will be combined with `done = false` from the view, which results in "show me all tasks that are done and not done at the same time" which won't work.

**Comment by dpschen** [comment]
This seems unintuitive for me as well.
Couldn't we extend, instead of combine the default filter?

Alternative (I think less preferable):
We should make it clear that the filter in the popup is combined with the default list view filter and also show that default filter. Currently there is no visual indication what the value of the default filter is, so the user would need to hold that value in his memory and combine it in his head to be able to understand the resulting query.

**Comment by kolaente** [comment]
I've added a message in 796199827e001614c33c2cd1a2fa72a94a67c345 - when the view has a filter configured, it will be shown below the filter input along with a notice that both will be combined.
