### ISSUE TITLE
URL in description field makes assumptions about the schema url

### ISSUE THREAD

**Issue by Heiss** [go-vikunja/vikunja#306]
### Description

If you enter a link, which does not start with `http(s)`, it removes the link after save. It shows it first, but after a page reload, the link is gone. This behaviour is unexpected, because this is an assumption about links and i would like to use links to open up the tool obsidian with the following `obsidian://open?file=Home.md`, also this disable the description field for other use cases like links to email programs etc.

Removing this assumption would open up the tool to local url schemas, but unfortunality this could be a security issue. But big players like todoist does have this functionality, so maybe it is not so big as first expected.

### Vikunja Version

v0.24.1

### Can you reproduce the bug on the Vikunja demo site?

Yes

**Comment by kolaente** [comment]
Fixed in e2a87036e070305291fd7ac1cfc9fe02c847b697. However, it looks like [this was recently broken in Tiptap](https://github.com/ueberdosis/tiptap/issues/5468) - the implementation in Vikunja will not work until [their fix](https://github.com/ueberdosis/tiptap/pull/5470) is merged, released and updated in Vikunja.
