### ISSUE TITLE
OpenID users can't join as an Admin of a Team

### ISSUE THREAD

**Issue by vish9812** [go-vikunja/vikunja#327]
### Description

As per the [docs](https://vikunja.io/docs/openid#automatically-assign-users-to-teams), there should be an option to manager team membership.

> If the vikunja_groups is part of the ID token, Vikunja will start the procedure and import teams and **team memberships**.

However, the `vikunja_groups` scope structure doesn't have any option to pass such memberships.

```json
{
    "vikunja_groups": [
        {
            "name": "team 3",
            "oidcID": 33349,
            "description": "My Team Description",
            "isPublic": true
        },
    ]
}
```

Currently, all users shows as "member" by default.

**Expected**: There should be a field like "membership" to pass "admin" or "member" to assign the team membership.

Also, is there any concept of "overall/global" admin in this app?

### Vikunja Version

0.24 (db411e036aed)

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment]
The docs may be a little unclear here, it is meant that Vikunja will create the teams and the membership automatically. These teams do not have an admin because the team is entirely managed by the oidc provider. This is intended behaviour.

> Also, is there any concept of "overall/global" admin in this app?

There [are plans to extend Vikunja so that it does](https://community.vikunja.io/t/vikunja-as-a-business/2345) but currently there is no such concept.
