### ISSUE TITLE
Comments pagination in a task

### ISSUE THREAD

**Issue by PedroERZ** [go-vikunja/vikunja#329]
### Description

I am having problems with pagination in the comments of my task, according to the tables in the DB there are more than 600 comments, but in the page view only 50 are shown, the rest are “hidden”, pagination should be enabled at this point but it does not happen

### Vikunja Version

Vikunja api version v0.23.0 Built with go1.21.7

### Can you reproduce the bug on the Vikunja demo site?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/1334a393-0732-4753-9de9-880e29994da9)

![image](https://github.com/user-attachments/assets/582b1abd-6663-4d9c-914e-5bde77781ba7)

**Comment by kolaente** [comment]
Fixed in https://github.com/go-vikunja/vikunja/commit/54994a1671e0093f71476dcff84144e0ac37d941, please check with the next unstable build (should be ready for deployment in ~45min, also on [try](https://try.vikunja.io)).

It's amazing how comments have been a thing in Vikunja since almost 5 years, and yet no one has noticed the pagination does not work.
